"""sueldo_nullable_and_job_comments

Revision ID: 25a31c3acac0
Revises: 91109f9eb038
Create Date: 2026-09-27 16:34:13.057046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a31c3acac0'
down_revision: Union[str, Sequence[str], None] = '91109f9eb038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_comments_id'), 'job_comments', ['id'], unique=False)
    op.create_index(op.f('ix_job_comments_job_id'), 'job_comments', ['job_id'], unique=False)
    with op.batch_alter_table('jobs') as batch_op:
        batch_op.alter_column('sueldo_semanal_libre',
                   existing_type=sa.FLOAT(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs') as batch_op:
        batch_op.alter_column('sueldo_semanal_libre',
                   existing_type=sa.FLOAT(),
                   nullable=False)
    op.drop_index(op.f('ix_job_comments_job_id'), table_name='job_comments')
    op.drop_index(op.f('ix_job_comments_id'), table_name='job_comments')
    op.drop_table('job_comments')
    # ### end Alembic commands ###
