"""add_vacancy_claims

Revision ID: 2a9c187dbda0
Revises: e86015c3be6b
Create Date: 2026-09-27 21:57:13.879117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9c187dbda0'
down_revision: Union[str, Sequence[str], None] = 'e86015c3be6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('claimed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verification_method', sa.String(length=20), nullable=False),
    sa.Column('verification_target', sa.String(length=255), nullable=False),
    sa.Column('verification_code_hash', sa.String(length=255), nullable=True),
    sa.Column('verification_attempts', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_claims_company_id'), 'vacancy_claims', ['company_id'], unique=False)
    op.create_index(op.f('ix_vacancy_claims_id'), 'vacancy_claims', ['id'], unique=False)
    op.create_index(op.f('ix_vacancy_claims_job_id'), 'vacancy_claims', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_claims_job_id'), table_name='vacancy_claims')
    op.drop_index(op.f('ix_vacancy_claims_id'), table_name='vacancy_claims')
    op.drop_index(op.f('ix_vacancy_claims_company_id'), table_name='vacancy_claims')
    op.drop_table('vacancy_claims')
    # ### end Alembic commands ###
