"""add_terminos_aceptados_at_to_users

Revision ID: 36e521529d4c
Revises: cdd32aa38bd4
Create Date: 2026-09-29 07:59:07.094693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e521529d4c'
down_revision: Union[str, Sequence[str], None] = 'cdd32aa38bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terminos_aceptados_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terminos_aceptados_at')
    # ### end Alembic commands ###
