"""add genero to user

Revision ID: 3ade9200df9f
Revises: 5367e38e84fb
Create Date: 2026-09-25 12:15:57.959558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ade9200df9f'
down_revision: Union[str, Sequence[str], None] = '5367e38e84fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('genero', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'genero')
    # ### end Alembic commands ###
