"""add_analytics_tables

Revision ID: 3ed2b53a3ef7
Revises: 960094f7e1ae
Create Date: 2026-09-28 15:19:34.621119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed2b53a3ef7'
down_revision: Union[str, Sequence[str], None] = '960094f7e1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_active_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_dau')
    )
    op.create_index(op.f('ix_daily_active_users_date'), 'daily_active_users', ['date'], unique=False)
    op.create_index(op.f('ix_daily_active_users_id'), 'daily_active_users', ['id'], unique=False)
    op.create_table('job_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'user_id', 'date', name='uq_job_view')
    )
    op.create_index(op.f('ix_job_views_date'), 'job_views', ['date'], unique=False)
    op.create_index(op.f('ix_job_views_id'), 'job_views', ['id'], unique=False)
    op.create_index(op.f('ix_job_views_job_id'), 'job_views', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_views_job_id'), table_name='job_views')
    op.drop_index(op.f('ix_job_views_id'), table_name='job_views')
    op.drop_index(op.f('ix_job_views_date'), table_name='job_views')
    op.drop_table('job_views')
    op.drop_index(op.f('ix_daily_active_users_id'), table_name='daily_active_users')
    op.drop_index(op.f('ix_daily_active_users_date'), table_name='daily_active_users')
    op.drop_table('daily_active_users')
    # ### end Alembic commands ###
