"""add_job_reports

Revision ID: 3ed20b7f8f07
Revises: 2a9c187dbda0
Create Date: 2026-09-28 10:04:04.278419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed20b7f8f07'
down_revision: Union[str, Sequence[str], None] = '2a9c187dbda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'user_id', name='uq_job_report')
    )
    op.create_index(op.f('ix_job_reports_id'), 'job_reports', ['id'], unique=False)
    op.create_index(op.f('ix_job_reports_job_id'), 'job_reports', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_reports_job_id'), table_name='job_reports')
    op.drop_index(op.f('ix_job_reports_id'), table_name='job_reports')
    op.drop_table('job_reports')
    # ### end Alembic commands ###
