"""add_photo_job_fields_and_aura_tables

Revision ID: 5367e38e84fb
Revises: i0d1e2f3a4b5
Create Date: 2026-09-25 10:18:51.474836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5367e38e84fb'
down_revision: Union[str, Sequence[str], None] = 'i0d1e2f3a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aura_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aura_events_id'), 'aura_events', ['id'], unique=False)
    op.create_index(op.f('ix_aura_events_user_id'), 'aura_events', ['user_id'], unique=False)
    op.create_table('user_aura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('total_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vacantes_reportadas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('colocaciones_ayudadas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_aura_email'), 'user_aura', ['email'], unique=False)
    op.create_index(op.f('ix_user_aura_id'), 'user_aura', ['id'], unique=False)
    op.create_index(op.f('ix_user_aura_user_id'), 'user_aura', ['user_id'], unique=True)
    op.create_index(op.f('ix_candidate_favorites_id'), 'candidate_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_chat_blocks_id'), 'chat_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_company_documents_id'), 'company_documents', ['id'], unique=False)
    op.add_column('jobs', sa.Column('origen', sa.String(length=30), server_default='empresa', nullable=False))
    op.add_column('jobs', sa.Column('fuente_contacto_telefono', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('fuente_contacto_email', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('fuente_contacto_whatsapp', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('foto_original_url', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('reportada_por_email', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('texto_ocr', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'texto_ocr')
    op.drop_column('jobs', 'reportada_por_email')
    op.drop_column('jobs', 'foto_original_url')
    op.drop_column('jobs', 'fuente_contacto_whatsapp')
    op.drop_column('jobs', 'fuente_contacto_email')
    op.drop_column('jobs', 'fuente_contacto_telefono')
    op.drop_column('jobs', 'origen')
    op.drop_index(op.f('ix_company_documents_id'), table_name='company_documents')
    op.drop_index(op.f('ix_chat_blocks_id'), table_name='chat_blocks')
    op.drop_index(op.f('ix_candidate_favorites_id'), table_name='candidate_favorites')
    op.drop_index(op.f('ix_user_aura_user_id'), table_name='user_aura')
    op.drop_index(op.f('ix_user_aura_id'), table_name='user_aura')
    op.drop_index(op.f('ix_user_aura_email'), table_name='user_aura')
    op.drop_table('user_aura')
    op.drop_index(op.f('ix_aura_events_user_id'), table_name='aura_events')
    op.drop_index(op.f('ix_aura_events_id'), table_name='aura_events')
    op.drop_table('aura_events')
    # ### end Alembic commands ###
