"""add_job_external_clicks

Revision ID: 6e5cfcb5dfaa
Revises: f4b9dc57488d
Create Date: 2026-09-29 18:24:50.770029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5cfcb5dfaa'
down_revision: Union[str, Sequence[str], None] = 'f4b9dc57488d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_external_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_external_clicks_id'), 'job_external_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_job_external_clicks_job_id'), 'job_external_clicks', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_external_clicks_job_id'), table_name='job_external_clicks')
    op.drop_index(op.f('ix_job_external_clicks_id'), table_name='job_external_clicks')
    op.drop_table('job_external_clicks')
    # ### end Alembic commands ###
