"""add_job_photo_logs

Revision ID: 91109f9eb038
Revises: 3ade9200df9f
Create Date: 2026-09-26 18:06:20.769720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91109f9eb038'
down_revision: Union[str, Sequence[str], None] = '3ade9200df9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_photo_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_photo_logs_id'), 'job_photo_logs', ['id'], unique=False)
    op.create_index(op.f('ix_job_photo_logs_job_id'), 'job_photo_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_photo_logs_user_id'), 'job_photo_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_photo_logs_user_id'), table_name='job_photo_logs')
    op.drop_index(op.f('ix_job_photo_logs_job_id'), table_name='job_photo_logs')
    op.drop_index(op.f('ix_job_photo_logs_id'), table_name='job_photo_logs')
    op.drop_table('job_photo_logs')
    # ### end Alembic commands ###
