"""add_company_logos

Revision ID: 960094f7e1ae
Revises: 3ed20b7f8f07
Create Date: 2026-09-28 15:07:40.764112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960094f7e1ae'
down_revision: Union[str, Sequence[str], None] = '3ed20b7f8f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_logos_company_id'), 'company_logos', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_logos_id'), 'company_logos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_logos_id'), table_name='company_logos')
    op.drop_index(op.f('ix_company_logos_company_id'), table_name='company_logos')
    op.drop_table('company_logos')
    # ### end Alembic commands ###
