"""add_job_likes

Revision ID: e86015c3be6b
Revises: 25a31c3acac0
Create Date: 2026-09-27 16:48:59.672262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86015c3be6b'
down_revision: Union[str, Sequence[str], None] = '25a31c3acac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'user_id', name='uq_job_like')
    )
    op.create_index(op.f('ix_job_likes_id'), 'job_likes', ['id'], unique=False)
    op.create_index(op.f('ix_job_likes_job_id'), 'job_likes', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_likes_job_id'), table_name='job_likes')
    op.drop_index(op.f('ix_job_likes_id'), table_name='job_likes')
    op.drop_table('job_likes')
    # ### end Alembic commands ###
