"""add_platform_videos

Revision ID: f4b9dc57488d
Revises: 36e521529d4c
Create Date: 2026-09-29 14:42:57.081162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b9dc57488d'
down_revision: Union[str, Sequence[str], None] = '36e521529d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tiktok_url', sa.String(length=500), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_videos_id'), 'platform_videos', ['id'], unique=False)
    op.create_table('user_video_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['platform_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_video_queue_id'), 'user_video_queue', ['id'], unique=False)
    op.create_index(op.f('ix_user_video_queue_user_id'), 'user_video_queue', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_video_queue_user_id'), table_name='user_video_queue')
    op.drop_index(op.f('ix_user_video_queue_id'), table_name='user_video_queue')
    op.drop_table('user_video_queue')
    op.drop_index(op.f('ix_platform_videos_id'), table_name='platform_videos')
    op.drop_table('platform_videos')
    # ### end Alembic commands ###
